web:
  repository: 'quay.io/wikimedia-quarry/quarry'
  tag: pr-79 # web tag managed by github actions

worker:
  repository: 'quay.io/wikimedia-quarry/quarry'
  tag: pr-79 # worker tag managed by github actions
